### ISSUE TITLE
Brent root finder fails to find roots

### ISSUE THREAD

**Issue by naasking** [mathnet/mathnet-numerics#1001]
Hello, ran into a situation where Brent's root finder failed to find roots, which you can see in the following program:

        static void Main(string[] args)
        {
            var x = new[] {      0,  845.4,   1703,   2459,   3389, 4285.3, 5006.2, 5982.4, 6710.9, 7593.5, 8188.1, 9181.2, };
            var y = new[] { 1.8853, 1.8618, 1.8414, 1.8213, 1.8013, 1.9701, 1.8326, 1.6421,  1.415, 1.0214, 0.6688,      0, };
            var f = CubicSpline.InterpolateNaturalSorted(x, y);
            var y0 = 1.79;
            var x0 = Brent.FindRoot(x1 => f.Interpolate(x1) - y0, 3000, 5800, 0.001, 1000);
            Console.WriteLine($"x0 = {x0}, y0 = {y0}, y(interpolated) = {f.Interpolate(x0)}");
            Console.ReadLine();
        }

There's a clear peak at x=4285.3, y=1.97, but no matter how many iterations I specify or how accurate/inaccurate the match, it can't find a root. It can find a root if I narrow the search range to 3800-5800, or if the y0 < 1.79.

Not sure if this is expected with this method, but it was surprising.

**Comment by jkalias** [comment]
Hi,

It seems you hit a nasty corner with this choice of points and target value `y0`. According to the [implemenation](https://github.com/mathnet/mathnet-numerics/blob/bc0bd6e4b33b8f58e99ff854755b4a3220881a84/src/Numerics/RootFinding/Brent.cs#L97) you need to have a changing sign so that the algorithm works.

If you plot the spline interpolation, you will see that for 1.79 you can have multiple roots, and your initial range selection (3000, 5800) hits two y points, which have the same sign.
![image](https://user-images.githubusercontent.com/942804/230465339-a2b8525c-67b7-4704-8d5d-2270bba8464f.png)

I'm not sure this helps you

**Comment by naasking** [comment]
Interesting, thanks. I didn't see that described in the documentation and hadn't looked into the code. I had already resolved this by switching to Newton-Raphson awhile back, but thought it might be worth lodging a ticket. Feel free to close if this isn't going to influence the code at all.

**Comment by jkalias** [comment]
I agree that this is a bit frustrating, but it is a common limitation of bracketing methods.

I don’t see a valid way of enhancing a general purposing library like Numerics to deal with such issues. You can safely close the ticket, thanks for the effort and your time.
