### ISSUE TITLE
Support for 0 lenght Vector and 0 by 0 Matrix

### ISSUE THREAD

**Issue by Gregor959** [mathnet/mathnet-numerics#134]
Not having 0 length Vectors and 0 by 0 Matrices creates many issues and porting issues from other libraries / code that handled 0 length Lists/ Vectors.

I am not sure what the original reasons were for not supporting 0 length Vectors and Matrices.
Every time on creates a vector from an array or enumerable on needs to check if that is not an empty collection and if it is an empty collection one has to return  null instead of a 0 length Vector and this creates lots of nulls objects in the code.

**Comment by krcook** [comment]
I would second this requirement - since not having this capability makes porting code to Math.Net very messy, as the user of the matrix has to keep track of number of rows and columns so that when rows/columns are added it knows what size to create it at.  In addition to the original request, it's important to also support matrices of (0 x n) and (n x 0) where n > 0.

**Comment by Evangelink** [comment]
@cdrnet I'd like to have a look at adding this feature. Do you have any preference between:
- allowing size 0 row/column for `Vector`/`Matrix`
- adding an `Empty` property for `Vector` and `Matrix`

**Comment by krcook** [comment]
I favour allowing size 0 row/column for vector/matrix.   
I've tried removing the restriction on creating such vectors/matrices, and it doesn't on the face of it seem to cause any issues - but this hasn't been tested comprehensively.

**Comment by kaba2** [comment]
I second that having zero-size vectors and matrices is an important feature. The lack of them causes a proliferation of special cases for no reason.
