### ISSUE TITLE
Update MathNet.Numerics.MKL* to Intel MKL 11.2 Update 1

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#270]
We are seeing an unmanaged memory leak in our application and it seems to be related to using MathNet.Numerics with MKL enabled.

If this issue is directly in MKL then it should be fixed with the update, if not we have to dig deeper into MathNet.Numerics native provider.

**Comment by tibel** [comment]
Good news `FreeBuffers()` solves our problem.

**Comment by cdrnet** [comment]
Great, thanks for the update!

**Comment by electricFeel** [comment]
@cdrnet  Sorry to resurrect this but I was curious about the implementation of the MKL native and why it would be necessary to call FreeBuffers (I just ran into the same issue). Will calling FreeBuffers delete *all* the buffers or just the ones whose references (Matrix objects) have been GC'd? The API documentation simply states that the buffers in the memory pool will be freed. 

Also, is there a reason that the specific allocated buffers aren't tied to the life cycle of the corresponding object? I'm only asking because calling FreeBuffers (albeit minor) is something that needs to be taken into account if using the MKL provider and will require some additional life-cycle management code if moving from the managed provider.
