### ISSUE TITLE
Bug in MatrixStorage.ClearColumns

### ISSUE THREAD

**Issue by MattHeffron** [mathnet/mathnet-numerics#284]
The ClearColumns() method in LinearAlgebra.Storage.MatrixStorage is using the wrong limit for the loop index into the passed array of columnIndices:
uses: ColumnCount
should be: columnIndices.Length

Compare with the ClearRows() method.

I also note that neither of these methods range check the column/row index values in the passed array(s).

**Comment by cdrnet** [comment]
* [ ] `MatrixStorage.Clear(ri,rc,ci,cc)` should also do proper range checks.
* [ ] the actual concrete storage provider overloads of these three methods should also be verified.

**Comment by cdrnet** [comment]
I've fixed the first part which is the actual bug.

Note that MatrixStorage is not intended to be called from user code directly. It is intentional that the arrays are not checked in this place (they are checked in the Matrix class). However, it is indeed inconsistent with its newer members which either do check ranges or have the `Unchecked` suffix (and are internal). I think we should apply the same pattern here as well.
