### ISSUE TITLE
Usage of new/delete in native code

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#325]
I think we should not use `new` and `delete` operator in the native providers.
When `new` cannot allocate the memory a `std::bad_alloc` is thrown.

.NET _DllImport_ uses _C export_ and throwing C++ errors over a C ABI is not nice.
E.g. for MKL `mkl_malloc` and `mkl_free` could be used instead (https://software.intel.com/en-us/node/522107).

**Comment by cuda** [comment]
great suggestion!

**Comment by tibel** [comment]
- [ ] Common (`Clone` in `lapack_common.h`)
- [ ] ATLAS
- [ ] CUDA
- [ ] MKL
- [ ] OpenBLAS

**Comment by tibel** [comment]
@cuda I haven't done C/C++ development for a long time. Adding more exit (return) points to the methods will make them less readable and harder to maintain. Do you have an idea how to solve this (e.g. using goto statements)?

**Comment by cuda** [comment]
I have an idea, I'll tinker with it in a couple days.

**Comment by tibel** [comment]
My version (with lack of better C/C++ knowledge) for MKL: 
https://gist.github.com/tibel/9f1de1447d4bb01670c9

**Comment by cuda** [comment]
that would work, but I wonder if we could use unique_ptr with a custom deleter and exceptions (but handle them inside the native library)
maybe something like this (compiles, but not really tested)
https://gist.github.com/cuda/3b164db015cf00c4580c

**Comment by tibel** [comment]
I think that the MKL functions do not throw any exception.
Do you think it is needed to introduce exceptions for MathNet memory allocations only?

**Comment by cuda** [comment]
>I think that the MKL functions do not throw any exception.
they don't, I threw one if the allocation failed.

>Do you think it is needed to introduce exceptions for MathNet memory allocations only?
In my opinion, yes. I think the code is cleaner with exceptions.

**Comment by kjbartel** [comment]
This is also related to the #316 changes which are currently using an approach similar to @tibel did in his gist.

**Comment by cuda** [comment]
Thanks, I haven't looked at CUDA provider. Whatever approach you guys thinks is best.

**Comment by kjbartel** [comment]
> Whatever approach you guys thinks is best.

I was thinking the same thing. I just wanted to point out that the CUDA provider recently had similar changes for handling memory allocation errors. So whichever approach is used should be consistent for all the native providers.

I don't have a lot of experience with native C++ programming so I'm not sure if it's better to use exceptions or not. Being a C# programmer the exceptions feel more natural and using macros with `goto` statements is harder to debug so I'd be inclined to use exceptions if there aren't any problems.

**Comment by tibel** [comment]
@cuda I'm worried about this workflow:
- throw a C++ exception
- catch it
- give back a return_code
- throw a C# exception

But: I'm OK with every version that works.

**Comment by redknightlois** [comment]
If you are dealing with the boundary between C/C++ and managed code, the best is to respond with an error code. There is no guarantee for C++ exceptions to be properly marshaled across boundaries.

**Comment by cuda** [comment]
@tibel That should only happen in rare occasions, unable to allocate memory. I'm not a fan of macros and goto's. The lapack code is C++ so why not take advantage of C++ features?  

@redknightlois yes, that is what are trying to correct. Currently, the code does throw across boundaries. What I suggested, wouldn't.

**Comment by cuda** [comment]
but as @kjbartel  pointed out, we should be consistent across all the providers. So, if using macros and gotos are better for the other providers, I'm fine with using them.

**Comment by kjbartel** [comment]
@cuda The changes for CUDA in #316 haven't been merged in yet so they could be changed to use exceptions.
Since we'll be wanting to return status codes from all native providers perhaps it would be better to settle on common codes which can be returned and handled by all the native providers in the same way. Therefore the native wrappers would throw and catch exceptions specific to the library and return one of the common error codes to C#. Other than memory allocation errors I'm not sure what else there would be though. Success, Failure, Memory allocation failure?

**Comment by redknightlois** [comment]
In CUDA you will have also very specific ones that dont exist on other providers. If you plan to write your own custom code, which makes sense in some places, you will find compilation issues, drivers hangs (it happens), argument validation on errors, etc.

**Comment by tibel** [comment]
@cuda You are right. It won't be the normal case that exceptions are thrown. +1 for your suggested implementation.

I agree with @kjbartel to be consistent across the providers. But keep in mind that the managed provider class (e.g. `MklLinearAlgebraProvider`) is part of the provider. So every native provider can have it's own return codes and the managed provider handles them and throws "consistent" C# exceptions.

**Comment by cuda** [comment]
I'll do some further testing this weekend to make sure this approach actually works.

**Comment by cuda** [comment]
seems to work. Making the change to the MKL provider along with switching to the high-level LAPACKE C interface so MKL will handle all the work arrays (take care of #325 (for MKL), #326, and  #327).

**Comment by tibel** [comment]
@cuda Thanks. I'm looking forward to see your changes.

**Comment by cuda** [comment]
I pushed a first take to https://github.com/cuda/mathnet-numerics/tree/memory

It is just the native side to see if the tests pass with smart pointers and LAPACKE, they do (the exports still have the work arrays so the managed code runs unmodified). I'll go over it again and then work on the managed side.

**Comment by cuda** [comment]
pushed an updated version...it now covers both the native and managed sides for all functions. Any feedback would be appreciated.

I disabled the direct provider tests for MKL, since some of the ones calling the work array functions (which no longer exist in the MKL provider) were having issues. That should be fine for the moment, since the regular unit tests should be hitting everything. All the LA tests pass, but some Broyden rooting tests are failing. The new info return values are saying that incorrect parameter values are being passed to it. I'll look into to it in a couple weeks (I'll be out of town the 15-21).

The next step is to remove the work arrays from the ILinearAlgebraProvider interface. I'll update the OpenBLAS provider to also use LAPACKE. It is supposed to support it, if not, I'll move the work arrays to the native side. I'm guessing the CUDA provider doesn't (haven't looked) use local memory work arrays.

**Comment by kjbartel** [comment]
> pushed an updated version...it now covers both the native and managed sides for all functions. Any feedback would be appreciated.

Is that in your https://github.com/cuda/mathnet-numerics/tree/memory branch? I'm only seeing [72df0ed](https://github.com/cuda/mathnet-numerics/commit/72df0ede7a3e508d99e73135258c34707661acc7) from 9 days ago.

> I'll update the OpenBLAS provider to also use LAPACKE. It is supposed to support it, if not, I'll move the work arrays to the native side.

OpenBLAS does support LAPACKE. It doesn't have the functions like `mkl_malloc` and `mkl_free` but there are a couple of `#define`s:

    #define LAPACKE_malloc( size ) malloc( size )
    #define LAPACKE_free( p ) free( p )

I think it's preferred to use `new`/`delete` than `malloc`/`free` though.

**Comment by cuda** [comment]
>Is that in your https://github.com/cuda/mathnet-numerics/tree/memory branch? I'm only seeing 72df0ed from 9 days ago.

That is the one. I squashed the newest commits onto the first one. Thought it would be easier to review if everything was on in one commit.

**Comment by cuda** [comment]
doh, if we remove the last couple MKL bits from the lapack.cpp, I wonder if we could just reuse that in OpenBLAS. I pushed quick test for MKL (it needs some refinement), moving the remaining MKL bits into MKL/lapack.h.

There we define two macros that specify the memory allocation and deallocation.
define PTRALLOC( size, alignment ) mkl_malloc( size, alignment )
define PTRFREE( p ) mkl_free( p )

so for OpenBLAS we might do something like
define PTRALLOC( size, alignment  ) LAPACKE_malloc( size )
define PTRFREE( p ) LAPACKE_free( p )

and then hopefully, the rest of lapack.cpp can be used as is.

As I said, this needs some refinement. When I get back I'll try to get the macros to use new and delete,  maybe use constexpr instead of macros, and clean code at the top of lapack.cpp.

**Comment by kjbartel** [comment]
> if we remove the last couple MKL bits from the lapack.cpp, I wonder if we could just reuse that in OpenBLAS.

Should be able to. Indeed both the blas.c and lapack.cpp files could be shared between OpenBLAS and MKL. Each project would simply have different headers, `lapack.h` and `blas.h`, and the common header `lapack_common.h` and the `blas.c` and `lapack.cpp` files would be the same. Would make maintenance much easier.

So I think the `array_new`, `array_clone` and `ptrfree` should be moved back into `lapack.h` as they were in the previous commit. OpenBLAS could then define its own version using `new` and `delete` rather than `malloc` and `free`. And there'd be no need for defining `PTRALLOC` and `PTRFREE`.

Should be fairly simple. I could make the changes and send a pull request to your branch if you want.

**Comment by cuda** [comment]
>blas.c

When I was working on ATLAS, the CBLAS interface was different between MKL and ATLAS, so that wasn't possible. If they are the same between OpenBLAS and MKL, then yes of course. 

>Should be fairly simple. I could make the changes and send a pull request to your branch if you want.

Please do. Right, if you are using new/delete, then there is no need for the custom deleter and new would already thow a bad_alloc exception. But I think you could still leave array_clone in lapack.cpp, no?

**Comment by cuda** [comment]
removed that comment about ATLAS. Looks like that is no longer the case.

**Comment by kjbartel** [comment]
> If they are the same between OpenBLAS and MKL, then yes of course.

The only difference I can see is for the complex arguments. OpenBLAS uses `float*` and `double*` whereas MKL uses `void*`. As such OpenBLAS has a cast like `(float*)`. The cast wouldn't cause any problems for MKL so you could use exactly the same file as long as the naming of int and complex types are unified as you did with `lapack.cpp`.

> But I think you could still leave array_clone in lapack.cpp, no?

Yes you are right. And `ptr` also. Probably should call it `array_ptr` and `array_free` particularly in the case of using `new` and `delete` for OpenBLAS.

One question, if `blas.c` and `lapack.cpp` are shared between MKL and OpenBLAS do you think they should they be moved into the `Common` folder also?

**Comment by cuda** [comment]
>Probably should call it array_ptr and array_free

That makes sense. Please rename / change things as you see fit.

>do you think they should they be moved into the Common folder also?

Yes, they should be. Thanks.

**Comment by kjbartel** [comment]
I'll try and have a look at it tonight.

**Comment by kjbartel** [comment]
Ok I've submitted the [pull request](https://github.com/cuda/mathnet-numerics/pull/1). Seems to work all ok.

Let me know if you have any feedback.

**Comment by cuda** [comment]
A quick scan and it looks great. I'll take a deeper look next Tuesday. thanks!

**Comment by cuda** [comment]
I wasn't sure about the LAPACK_MEMORY define block in lapack_common.h, so I tweaked the headers a little. What do you think?

**Comment by kjbartel** [comment]
> I wasn't sure about the LAPACK_MEMORY define block in lapack_common.h

I wasn't 100% sure about it myself. My reasoning was that with `lapack.cpp` being shared and using `array_ptr`, `array_clone` and `array_new` I thought it better to have a default shared implementation of those functions in `lapack_common.h`, but allow their implementation to be overridden where needed (as is done in MKL). Other providers (ATLAS etc.) which also use new / delete could then use the default implementation without needing to copy the implementation from OpenBLAS (which wouldn't be immediately clear from looking just at the shared files or MKL).

ATLAS currently requires a non-shared version of `lapack.cpp` due to missing functions. One solution to this could be to split lapack.cpp into separate files, for example for lu, cholesky, qr, svd and eigen, and then almost all of the files can be shared among the providers with provider specific implementations be used where needed. I've also been playing around with some native vector functions for providers which don't have their own implementation.

**Comment by cuda** [comment]
OK, I see. I'll tinker with it bit more.

>. One solution to this could be to split lapack.cpp into separate files, for example for lu, cholesky, qr, svd and eigen, and then almost all of the files can be shared 

That is a good idea.

**Comment by cuda** [comment]
added back the LAPACK_MEMORY define but left the other minor tweaks (squashed the last couple fo commits) . I'll remove work arrays from the ILA provider interface this weekend.

**Comment by kjbartel** [comment]
> added back the LAPACK_MEMORY define but left the other minor tweaks

Just looked at the changes and it looks good to me.
