### ISSUE TITLE
MKL: Reason of allocating work array in managed code

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#326]
Why the work arrays for LAPACK (lu, qr, svd) are created in C# (managed code)?

I think they are needed only for the calculation (temporarily). When allocating them in native code we could benefit from the MKL memory pools and reduce stress of CLR memory allocator and GC.

**Comment by tibel** [comment]
The `work` array is an implementation detail of the provider and should not be part of the public interface. 
``` C#
ILinearAlgebraProvider<T>
{
  void LUInverse(T[] a, int order, T[] work);
  void LUInverseFactored(T[] a, int order, int[] ipiv, T[] work);
  void QRFactor(T[] a, int rowsA, int columnsA, T[] q, T[] tau, T[] work);
  void ThinQRFactor(T[] a, int rowsA, int columnsA, T[] r, T[] tau, T[] work);
  void QRSolve(T[] a, int rows, int columns, T[] b, int columnsB, T[] x, T[] work, QRMethod method = QRMethod.Full);
  void QRSolveFactored(T[] q, T[] r, int rowsA, int columnsA, T[] tau, T[] b, int columnsB, T[] x, T[] work, QRMethod method = QRMethod.Full);
  void SingularValueDecomposition(bool computeVectors, T[] a, int rowsA, int columnsA, T[] s, T[] u, T[] vt, T[] work);
}
```

When using CUDA the work array has to be allocated in graphics memory.

**Comment by cuda** [comment]
The original idea was to support creating a single work array in .NET, and use it over and over, instead of allocating one each time.  Yes, GPU providers couldn't use it, but they didn't need to support it (the same way the managed provider wouldn't in many cases). But I don't think we ever provided a way from the managed code to support reusing the a work array. So, I'm all for removing it from the public interface and requiring the providers to handle it themselves. I'll work on the MKL provider next week.

**Comment by tibel** [comment]
Thanks for fixing this.
