### ISSUE TITLE
MathNet.Numerics.Statistics.ArrayStatistics.Single.RanksInplace returns double[]

### ISSUE THREAD

**Issue by atlemann** [mathnet/mathnet-numerics#364]
MathNet.Numerics.Statistics.ArrayStatistics.Single.RanksInplace takes a float[], but returns double[], which is a bit inconsistent and inconvenient.

Change the return type to float[]?

**Comment by cdrnet** [comment]
This is intentional in general for all descriptive statistics based on floats, to avoid loosing precision unnecessarily. However, I agree that for order statistics it is indeed somewhat questionable. Unfortunately this has been released, so we cannot simply change the return type until the next major version (semantic versioning).

**Comment by cdrnet** [comment]
I took the chance of the upcoming v4 release to finally fix this. Thanks for bringing it up.

**Comment by atlemann** [comment]
Cool, thanks! Then I can eventually go remove some casts 😊
