### ISSUE TITLE
Erf.cs: performance issues

### ISSUE THREAD

**Issue by Yenyenx** [mathnet/mathnet-numerics#365]
Hi,
I have been using the Normal distribution coded in MathNet.Numerics a lot lately and profiling tests reveal a lack of computational performance especially in Erf.cs. I have been looking through the code and was wondering why the static functions coded in Erf.cs do not use static parameters instead of double arrays initialized at each function call... It could be a significant improvement in computational speed and won't in any way alter the numerical accuracy or thread safety of the code.
What do you think ?

**Comment by cdrnet** [comment]
Yes, I agree, we should change that!

**Comment by Jdsleppy** [comment]
Hello.  I would like to take on this issue as my first contribution if nobody has claimed it yet, mainly because it is straightforward and I understand the purpose well.  I will look to Gamma.cs and ModifiedBessel.cs as guidelines for formatting since those classes also have static coefficient arrays.

Let me know if this issue is already being worked on or if there is something else I should know.

**Comment by cdrnet** [comment]
Implemented in #369
