### ISSUE TITLE
Vector.ToRowMatrix Rename to Vector.Transpose

### ISSUE THREAD

**Issue by drcrook1** [mathnet/mathnet-numerics#396]
I would like to suggest this rename.  It makes more sense from a mathematical terminology.  I was looking for transpose for nearly an hour and then started trying to implement from scratch.

let v = vector [ 1.0; 2.0; 3.0 ]
v.ToRowMatrix() * v

If not renaming due to the minor mathematical discrepency, perhaps adding Vector.Transpose.  I mean its a pretty common operation.

**Comment by cdrnet** [comment]
Note that vectors in Math.NET Numerics are neutral by design, neither strictly _row_ nor _column_. `Transpose` would therefore return the vector unchanged, that's why it is omitted. There's typically one very common and a few rare combination use cases, making using vectors quite a bit more convenient to use in practice (confirmed by common feedback). Renaming `ToRowMatrix` as `Transpose` would therefore be misleading, since it could also have been assumed to be a row by the application.

- Dot Product (row*column, common): `v*v`, or `DotProduct` function, both return a scalar
- Outer Product (column*row, rare): `OuterProduct` function, returns matrix
- Pointwise Product (same*same, rare): `PointwiseMultiply` function (or `v.*v` in F#).

So in your case you don't actually need to call this function, simply use the product `v*v` - that is, unless you'd want the result to be a single-value vector instead of a scalar.

Of course there are cases where you'd wish to explicitly and strictly distinguish and handle row and column vectors. In this case I recommend to use single-row/column matrices instead.
