### ISSUE TITLE
Visualization tool

### ISSUE THREAD

**Issue by kapil-iitk** [mathnet/mathnet-numerics#420]
Is there is open-source visualization tool available (like microsoft chart or ILNumerics) for the plotting of the data. The main concern is the size of the library. Which tool you are using for the scientific visualization.

**Comment by Superbest** [comment]
Why did you close this? Did you find a tool?

By the way, I use ggplot2 with R (Rstudio) for visualizing. It's very powerful and keeps things tidy even for complicated plots. Presumably you could dump your data to a text file and feed into the R script.

**Comment by kapil-iitk** [comment]
Hello,
I am using microsoft chart for the simple data visualization. Also, I am using python, NumPY and Matplotlib for the scientific calculation and visualization. The main issue with such things are huge package and speed. 

I am looking for a simple visualization library (like ILNumerics) which is compatible with the  numerics datatype and must be open sourced.

**Comment by PawelTroka** [comment]
You could try my private project [Computator.NET](https://github.com/PawelTroka/Computator.NET), which is using MathNet.Numerics.

**Comment by kapil-iitk** [comment]
@PawelTroka  Thank you for your response. Computator.NET is a nice tool. But I need a library that can be used for the data visualization (similar to microsoft chart or ILNumerics etc)
Thank you

**Comment by cdrnet** [comment]
Note that Math.NET Numerics itself does intentionally not provide anything related to visualization by itself. I think it would be a fatal design mistake to couple algorithms and data structures with application and user interface concerns like visualizations.

I'm closing this here since it is not technically an issue within Numerics, but feel free to open a topic on this in [discuss.mathdotnet.com](http://discuss.mathdotnet.com) to discuss some options. It could also be a good idea to publish some of them on the website.
