### ISSUE TITLE
Repackage for .net core

### ISSUE THREAD

**Issue by affans** [mathnet/mathnet-numerics#421]
Is it possible to repackage for the new .net core? I am currently using .net core to conduct some scientific research and using this package would be a great help.

Is there a way I can do this manually as well?

**Comment by cdrnet** [comment]
See #386.

**Comment by iamcarbon** [comment]
@cdrnet Anything holding this back that I can assist with? I'm working on porting a project over to dotnetcore and this is the final dependency to work out.

**Comment by cdrnet** [comment]
What is holding me back is mostly lack of understanding how I can set up a proper project file to explicitly target for one of the new NetStandard profiles, that works with the existing setup.

**Comment by cdrnet** [comment]
I essentially have a separate project file for each platform I target [here](https://github.com/mathnet/mathnet-numerics/tree/master/src/Numerics), side by side. What I would need is another project file e.g. for NetStandard1.0. Unfortunately this trivial requirement seems to be already beyond the capabilities of the new .Net Core tooling...

**Comment by iamcarbon** [comment]
Looks like adding a dotnetcore project alongside the others looks like it will work well until the tooling is unified with VS15.

Did a temporary fork to begin working out the reduced surface area. It looks like we'll need to do conditional completion around:

- RandomNumberGenerator (new RNGCryptoServiceProvider() -> RandomNumberGenerator.Create())
- [Serialization] (possibile shim as no-op -- until netstandard2 support)
- [TargetedPatchingOptOut]
- EndsWith, StartsWith (missing an overload)
 
to target netstandard1.0 (including Profile7, Profile31, Profile32, Profile44, Profile49, Profile78, Profile84, Profile111, Profile151, Profile157, & Profile259). 

Thoughts on expanding the portable conditional to exclude functionality outside of netstandard1.0 (specified above)?

e.g.
#if !PORTABLE
[Serialization]
#endif

Alternatively, we can create fine grained symbols to subset the features (e.g. #FEATURE_SERIALIZATION) OR add no-op shim. Although, long term -- I think it makes sense to just reduce the surface area of older frameworks and evolve with the standard. This will dramatically simplify cross targeting as the tooling matures.

**Comment by cdrnet** [comment]
Great - I'd be very interested to see your fork!

We currently have a mix between platform and feature compilation symbols, see [Platform Discrepancies](http://numerics.mathdotnet.com/Compatibility.html#Platform-Discrepancies). Maybe we can clean this up a bit. The symbols from the PCL259 project could be a starting point, but I'd like to support native providers in .Net Core in the end.

**Comment by sebandraos** [comment]
Is there anything an external developer like myself can do to help this along? This is our final dependency that isn't on .NetStandard. As far as I can tell the current netstandard branch works with an added reference to System.Runtime.Serialization.Primitives. Is there anything that can be easily cleaned up to make this a feature of the next release?

**Comment by cdrnet** [comment]
Thanks, that helped already.

Unfortunately all the other project files are now completely unusable.

**Comment by cdrnet** [comment]
In order to make the .Net Standard build really useful, it should also support native providers properly (which are stripped from the current PCL builds). For this, the following seems to be missing and we'd need an alternative for (or I am again missing some new package):

* Environment.Is64BitProcess (to load the matching provider build)
* Environment.GetEnvironmentVariable (PROCESSOR_ARCHITECTURE fall back, among others)
* Environment.OSVersion.Platform, PlatformID (to know whether we are on Unix or Windows)
* AppDomain.CurrentDomain.BaseDirectory (one of the places to look for the providers)
* Assembly.GetExecutingAssembly().Location (another place to look for the providers)
* Directory, FileInfo, Path.GetFullPath etc (seems I need at least .Net Standard 1.3 for this?)
* System.ComponentModel.Win32Exception
* System.Runtime.InteropServices.CharSet.Auto
* SuppressUnmanagedCodeSecurityAttribute

**Comment by cdrnet** [comment]
I theory it could be nice to separate native provider loading out into a separate package, such that the core could support a very low standard level like 1.1 while the native parts require at least 1.3. But in practice I expect everyone will move forward to standard 2.0 in a couple months anyway, where this distinction is no longer relevant. Any thoughts on this?

**Comment by cdrnet** [comment]
Most of the environment is now available via `RuntimeInformation`.

**Comment by sebandraos** [comment]
I think the two package idea is indeed a very good one but I imagine it requires a decent mount of work to get it ready.
You're absolutely right Christoph, the vast majority of people will probably target 2.0 given that it will be released in line with the proper tooling. Are you suggesting that Numerics should target 2.0 or that most people won't mind a target of 1.3 because they will be targeting 2.0?
I'm sure you're aware of APIPort [https://github.com/Microsoft/dotnet-apiport](url) which checks through the methods of a library or executable to determine support for different frameworks.

**Comment by cdrnet** [comment]
I've recently realized that unfortunately we must make sure that our .Net framework builds do not reference anything related to .Net Standard (which includes otherwise useful stuff like the new RuntimeInformation), or it would be impossible to continue providing them as cross-platform binaries.

Currently the net40 binaries I build on windows work directly also on Linux (and all kind of other systems), so I can directly copy (or share, e.g. with vagrant) my bin folder to Linux and it works out of the box. Unfortunately this will stop working as soon as these binaries reference anything .Net Standard.

**Comment by iamcarbon** [comment]
I've put together a solution to target .netcore (NETSTANDARD 1.0) along with build scripts to generate a nuget package. I'll spend some time later this week seeing how difficult it will be too enable support for the providers.

ref: #473

**Comment by iamcarbon** [comment]
Update: took a first stab supportive native providers on NETSTANDARD 1.3 with good luck. 

Still need to figure out a reliable way of determining if the process is running in 64bit mode, 
(checking the OS isn't enough), expanding support for the assembly locations, and catching EntryPointNotFoundExceptions. 

Everything else looks to be there and working well.

**Comment by wonea** [comment]
@iamcarbon RE the pull request (don't want to clutter things up). I'm working on a project building against .NETSTANDARD 1.6 and would very much appreciate a standard port. I'd rather not wait three months for .NETSTANDARD 2.0 and the new csproj format - and much rather a preview release now.

**Comment by sebandraos** [comment]
@iamcarbon Is there anything you can point to that would facilitate a first release of this? I can easily spare some time but I'm not sure what needs doing.

**Comment by iamcarbon** [comment]
@sebandraos Here's an unofficial release for now: https://www.nuget.org/packages/MathNet.Numerics.Core/

**Comment by sebandraos** [comment]
Thanks @iamcarbon that's really helpful. The offer still stands if there is anything you can point to but don't have the time to work on.

**Comment by sebandraos** [comment]
@iamcarbon It seems that that package still references System.IO.FileSystem and System.Security.Cryptography.Algorithms in .NETSTANDARD 1.1 which are incompatible with anything below 1.3. This has been corrected in the latest commits on #473 but these aren't reflected on the nuget. Just FYI and that of anyone else who comes looking for a sneak peek

**Comment by vpenades** [comment]
@iamcarbon the best way to know if you're running in a 64bit architecture is to do this:

`bool is64 = IntPtr.Size == 8;`

Btw, I am also looking forward for a pure Net Standard nuget package; after VS2017, all the portable profile project will be deprecated.

**Comment by sebandraos** [comment]
Any movement here? We've been running with MathNet.Numerics.Core for a while and it's working great.

**Comment by vpenades** [comment]
Also, keep in mind that targeting Net.Standard 2.0  severely limits the number of supported runtime platforms. 

In fact, in order to write a full cross platform application (Android+iOs+Windows Store) Net.Standard version must be 1.4 or less!

**Comment by wonea** [comment]
@vpenades only because UWP apps haven't caught up with the .NETStandard. UWP is lacking in this regard.

**Comment by tura08** [comment]
How are we looking on this?

**Comment by cdrnet** [comment]
My current position:
- I have/had a lot of concerns with .Net Standard 1.*, but most of them seem to be addressed by .Net Standard 2.0.
- I propose to skip .Net Standard 1.* support in the official package but to fully support .Net Standard 2.0.
- Keep the unofficial package listed for a while for those explicitly requiring .Net Standard 1.*
- Keep the PCL builds in the official package for a while for those targeting Android, iOs, Windows Store etc, at least until .Net Standard 2.0 is established and widely supported (which is likely years...).

But I'm open to change this if there are concerns. I try hard to avoid breaking any users, one of the reasons we still support .Net 3.5 (and still have users needing it) - but incidentally also one of the reason for skipping .Net Standard 1.* which I understand is basically technical dept the time it is added but will hurt for years to come to try to keep supporting it (when Microsoft has long abandoned it).

**Comment by vpenades** [comment]
As far as I know, net standard xx is about API surface coverage, not runtime, which means that net standard 2.0 is just a superset of net 1.xx.

Thinking about net standard in terms of net framework (the highest the number, the better) is incorrect. In fact my personal phylosophy towards net.standard is the opposite, the smallest the version, the better, as I have more chances for my assembly to run everywhere.

**Comment by cdrnet** [comment]
Yes, that was the original idea, which I agree is quite elegant in theory. Unfortunately it is only elegant in theory, not in practice (it adds _a lot_ of complexity for almost zero benefit), so it is being replaced with .Net Standard 2.0 which fixes most of the issues. I do not expect anyone will care about .Net Standard 1.* in one or two years since all platforms will support 2.0 anyway (or never supported .Net Standard); nor will Microsoft invest in 1.* tooling (the *.json stuff is deprecated already). This is at least my impression of the current state. Maybe my impression is biased?

On the other hand, if I can indeed target, say, .Net Standard 1.3 with only v2ff build tools, msbuild project system (no json) and without having to depend on 50 NuGet packages, I'm happy to target it officially as well.

**Comment by cdrnet** [comment]
Yes, this is a general principle for libraries like this, and is why we e.g. still primarily target .Net 4.0 instead of, say, 4.6.2. However, typically this only applies within the same major version (as in semantic versioning).

However, my impression is that for .Net Standard, v2.0 is not simply v1.* with more surface covered, but a make-over with lots of learnings fixed and improved, and developer complexity removed or hidden. I expect v1.* to be abandoned in a year or two since all platforms will support 2.0 anyway (or never supported .Net Standard in the first place) and doubt Microsoft will invest anything in 1.* tooling (the *.json stuff is deprecated already). But maybe my impression is biased?

On the other hand, if I can indeed target, say, .Net Standard 1.3 with only v2ff build tools, msbuild project system (no json) and without having to depend on 50 NuGet packages, I'm happy to target it officially as well.

> Regarding MathNet, an approach I've seen in other projects is to simply opt-out with #ifdefs the pieces of code that require higher net standard versions.

Yes, that's what we currently do already for our multi-targeting. It works ok.

**Comment by cdrnet** [comment]
A) Is there a concrete demand for .Net Standard 1.* (not satisfied by supporting .Net Standard 2.0)?
B) Do you expected to still need that in a year, or mainly to bridge until .Net Standard 2.0 is established?
C) If this is transient, is using the unofficial package an option until 2.0 is established?

**Comment by sebandraos** [comment]
Just my 2 cents: Personally I would make a distinction between the version number (1.x vs 2.0) and the tooling. Targeting a higher or lower version of .Net Standard with the new tooling, introduced with VS 2017, which has indeed thrown out the .json "stuff", is a really easy process including multi-targeting. Beyond that there may or may not be other major advantages to being on 2.0 vs 1.x

**Comment by westonpace** [comment]
.net standard 2.0 is out.  All platforms now support it except for UWP which has a preview build available.  I will give a +1 to your strategy.  Also, even if users are targetting .netstandard 1.0 I believe they can still use the portable profile with a warning.  I've been shipping a .NET Core 1.0 product with mathnet-numerics since January.  So my answers are

A) Not from me
B) N/A
C) N/A

**Comment by rlordcardano** [comment]
Fully agree with @westonpace !

**Comment by naraz** [comment]
@westonpace did you try to use mathnet-numerics together with Unity to build a UWP Project maybe?

**Comment by vpenades** [comment]
A) Personally, I like net.standard 1.1 for basic behaviour/pure logic/pure math development, because it's a natural sandbox, which is very convenient when third parties might require to inject plugins.  So, for assemblies that fit that functionality, I will keep targeting 1.1... 1.3 at best if I require file system access.

B) From my previous answer, yes.

C) N/A

**Comment by westonpace** [comment]
@naraz No, if you are saying that would allow for .netstandard 2.0 support than that is great.  I don't actually build against all platforms (only Windows & Linux) and was just going off [this table from Microsoft](https://github.com/dotnet/standard/blob/master/docs/versions.md).

@vpenades netstandard 1.1 allows for file I/O so it isn't the greatest sandbox.  1.3 is even worse as it allows for external process control (e.g. `System.Diagnostics.Process`).

**Comment by screig** [comment]
@iamcarbon with regards your package:

Exception thrown: 'System.Resources.MissingManifestResourceException' in System.Private.CoreLib.dll
Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "MathNet.Numerics.Properties.Resources.resources" was correctly embedded or linked into assembly "MathNet.Numerics.Core" at compile time, or that all the satellite assemblies required are loadable and fully signed.

**Comment by petriashev** [comment]
.netstandard 2.0 is the main target. versions 1.3-2.0 are intermediate as .net prior 4.6.1.
If you dont want to break old users u dont (just keep old packages), but all new packages must be netstandard2.0. If you can make it working on netstandard 1.x so package would support several versions. Missing netstandard is the real pain

**Comment by vpenades** [comment]
@petriashev There's no need to keep old packages to give support to users using versions lower than 4.6.1

You can have a nuget package targeting multiple versions of NetStandard, and older versions of NetFx. For example, NewtonSoft.Json supports many versions of NetStandard, and NetFX down to 3.5 and 2.0 at the same time, everything in a single package.

Another interesting example is SixLabors.ImageSharp. It supports NetStandard 1.1 and 1.3 in the same package. The idea is to give support as wide as possible, and add features incrementally. For example, ImageSharp NetStd1.1 can only read/write images from already open Stream objects, while 1.3 is able to read/write files from the file system... but ultimately, which actual assembly is used is automatically resolved by the compiler.

**Comment by cdrnet** [comment]
Closing this, since the first alpha releases of v4 with .Net Standard 1.3/2.0 support are out. Please let me know if you have any issues.

**Comment by rpawlaszek** [comment]
Is there a chance for a signed netstandard version of the package? The current [Signed](https://www.nuget.org/packages/MathNet.Numerics.Signed/) package is behind the [non-Signed](https://www.nuget.org/packages/MathNet.Numerics/) one.

**Comment by cdrnet** [comment]
@rpawlaszek yes, this is planned (strong name)
