### ISSUE TITLE
Master branch does not compile on mac and linux

### ISSUE THREAD

**Issue by florisvankempen** [mathnet/mathnet-numerics#538]
I cannot build a clean clone of the current Math.NET Numerics (master) on macOS using both the FAKE and msbuild methods indicated in the readme file. Actually, also the build server at Travis CI quits with the same error: [https://travis-ci.org/mathnet/mathnet-numerics](url)
The last version that could build successfully on linux seems to be v3.20.0 / commit 29550af, 6 months ago.

I could not find it in the issue tracker, but I suppose it is already known? Are there plans for supporting linux and macOS with v4 in the near future?

FAKE fails with:
`dotnet clean MathNet.Numerics.sln
﻿﻿Copyright (C) Microsoft Corporation. All rights reserved.
/home/travis/build/mathnet/mathnet-numerics/src/FSharpUnitTests/FSharpUnitTests.fsproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/home/travis/build/mathnet/mathnet-numerics/src/FSharpUnitTests/FSharpUnitTests.fsproj.metaproj'.`

msbuild fails with:
`Project "/Users/Floris/mathnet-numerics/src/Numerics/Numerics.csproj" (2) is building "/Users/Floris/mathnet-numerics/src/Numerics/Numerics.csproj" (2:2) on node 1 (Build target(s)).
PrepareForBuild:
  Creating directory "bin/Debug/net40/".
/usr/local/share/dotnet/sdk/2.0.3/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file '/Users/Floris/mathnet-numerics/src/Numerics/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/Users/Floris/mathnet-numerics/src/Numerics/Numerics.csproj]
  Build continuing because "ContinueOnError" on the task "ReportAssetsLogMessages" is set to "ErrorAndContinue".`

**Comment by cdrnet** [comment]
Yes, our [Travis](https://travis-ci.org/mathnet/mathnet-numerics) CI build also fails.

The first priority is to produce builds/packages that can be used on all platforms (using .Net Standard), i.e. to get v4 out. Once we're there and v4 is finally released, the second priority would then be to be able to build on these platforms again as well. We certainly want to get both CI builds green again, both AppVeyor/Win and Travis/Linux.

The change with v4 is that we build using the .Net Core SDK, while v3 on Linux was built with Mono tools. To be honest I have no idea what the problem is in the FAKE build - it does seem to affect only F# project, and might be related to project references to C# projects. If you have any idea, any hints would be appreciated. In theory on Linux/mac it should be enough to run `./restore.sh` and `dotnet build MathNet.Numerics.sln`.

**Comment by cdrnet** [comment]
Related issues:

- dotnet/cli#7000
- Microsoft/msbuild#2275
- Microsoft/msbuild#2022

**Comment by cdrnet** [comment]
I've managed to fix the build, at least on Travis CI, essentially by directly using MsBuild 15 instead of the dotnet cli tools wrapping it. Multi-targeting can then leverage Mono for the with .Net Framework builds.

**Comment by florisvankempen** [comment]
Great! I can confirm that I can get a successful build as well, using FAKE on macOS. After that ran once, it will also work with msbuild.

Thank you for the quick response and action!

**Comment by cdrnet** [comment]
Great, thanks for the update!

It might be enough to run `restore.sh` only, once, for msbuild to work afterwards.
