### ISSUE TITLE
Why separate packages for signed, strong-named assemblies?

### ISSUE THREAD

**Issue by mikevanoo-fsg** [mathnet/mathnet-numerics#561]
Hi,

This may have been covered before but searching here, the main website and the old CodePlex site, I couldn't find the answer. The couple of references I did find were:

"Strong naming has been dropped by choice, and I'd really prefer it to keep that way."
(https://archive.codeplex.com/?p=mathnetnumerics)

"I have not changed my mind on signing..."
(https://github.com/mathnet/mathnet-numerics/issues/140#issuecomment-25531687)

So, what are the reasons for separate packages for signed, strong-named assemblies? This causes a problem for us as we strong-name all of our assemblies so we can't reference the latest versions.

Thanks in advance,

Mike.

**Comment by cdrnet** [comment]
Hi Mike

Just curious, do you have a hard technical reason for strong naming, or is it merely due to a policy?

I think there are three points on this:

1. For completeness: Signed vs strong named. The strong named packages had the .Signed suffix in the name which is quite confusing. Indeed, all the packages including the main one are now signed properly, with a code signing certificate. But signing is unrelated to strong naming. I wish I had named these packages .StrongNamed instead of .Signed.

2. I don't want to strong name the main package assemblies. There are several reasons for this, which have been confirmed in my own experience numerous times over the last decade. In my experience, the problems strong naming causes outweight the problems caused by weak names by a **huge** margin. To be more precise, I think the problems are more related to assembly binding/fusion and binding redirects rather than the strong naming itself, but at least in .NET Framework the only way to avoid this special hell is not to strong name.

3. There is no more strong named package available for the v4 packages at this point, but I'm willing to start building them agin if this unblocks you. Would this work for your?

Thanks,
Christoph

**Comment by buybackoff** [comment]
Re:2 I likely have less experience, but remember binding hell only when am assembly changed its key. If the key is the same then all upgrades go smoothly. In my case I need strong name because a client app is strong named and I cannot make this library as a dependency. Supporting strong name with a public singing key in the repo is no more difficult than unsigned one. If you insist that you do want your main package be unsigned, I see now reason not to add a singed/strong named version in parallel, which is built and published simultaneously. With .NET Core it became impractical to pack multiple dlls in a single NuGet, so having a singed latest Math.Net already on Nuget is important, but it is not convenient to support a local fork just for that if the whole thing could be automated with minimal effort in the upstream.

**Comment by mikevanoo-fsg** [comment]
Hi @cdrnet , do you have an ETA on producing strong-named v4 packages please? Thanks.

**Comment by cdrnet** [comment]
Since v4.4.1 the .Signed packages are back (just published, currently pending validation...)

**Comment by StephenCleary** [comment]
@mikevanoo 

>  we want to know that what we are plugging in is the "correct" assembly" and not some dodgy substitute.

It is *very important* to make *very clear* that *strong-name signing does **not** provide **any** guarantees* that would detect tampering.

**Comment by WeihanLi** [comment]
Think it may be better to combine these two packages, it would be easy for developers to integrate, the `StackExchange.Redis` is publishing one package only, since v5 is a breaking change, maybe we could consider this? @cdrnet 

- https://github.com/StackExchange/StackExchange.Redis/issues/1537#issuecomment-662526729
- https://github.com/StackExchange/StackExchange.Redis/issues/528

**Comment by cdrnet** [comment]
Thanks, yes, we can always reconsider such decisions, and v5 would indeed be a good point in time.

However, binding redirects are still very painful today, so although this would make it a bit easier for some developers to integrate, it would make it more painful for others.

Looking at the numbers of the Numerics package, as of today overall about 5.9% of the total downloads were for the signed one. For the newest release 4.15 this dropped to only 2.2%. Because of these numbers I'd rather not make it more difficult for ~97% of the users just to make it a bit easier for ~3%. We'll continue providing signed packages with v5 for these 3% though, of course.

**Comment by WeihanLi** [comment]
Got it, thanks for your reply @cdrnet
