### ISSUE TITLE
StudentT.InvCDF return wrong (?) value.

### ISSUE THREAD

**Issue by Orace** [mathnet/mathnet-numerics#675]
Let's compute the inverse of the cumulative distribution of StudenT law.
With 8 degrees of freedom and a confidence level of 0.95.

Excel gives : 2,30600414
[a random online tool based on jstat](http://onlinestatbook.com/2/calculators/inverse_t_dist.html) gives: 2.306

MathNet.Numerics.Distributions gives:

```C#
  StudentT.InvCDF(0, 1, 8, 0.95);       // 1.8595480375315365
  StudentT.InvCDF(0, 1, 8, (0.95+1)/2); // 2.306004135204172
```

I don't know whats going on here but something is wrong somewhere.

**Comment by cdrnet** [comment]
`StudentT.InvCDF` implements the inverse cumulative distribution function of the [Student-T distribution](https://en.wikipedia.org/wiki/Student's_t-distribution). Excel seem to agree on the numbers: `T.INV(0.95;8)` returns 1.859548038, the same as Numerics.

However, you don't seem to be interested in the CDF directly, but instead in the probability of a variable being within a two-sided interval, i.e. `p = P(-t < x < t)`. You can express this probability using the CDF as difference `p = CDF(t) - CDF(-t)`. Since CDF itself is symmetric with `CDF(-x) = 1-CDF(x)`, this can be simplified to `p = 2*CDF(t)-1`. Indeed, `2*StudentT.CDF(0,1,8,2.306004)-1` returns 0.95.

Now, you're interested in the inverse, which is `t = InvCDF((p+1)/2)` as you had already figured out. Indeed, `StudentT.InvCDF(0.0, 1.0, 8.0, (0.95+1)/2)` does return 2.30600413520417.

Does that make it clearer?

**Comment by Orace** [comment]
Actually in Excel I was talking about `LOI.STUDENT.INVERSE` ... Yep a French version of Excel give French method name.
It appears that `LOI.STUDENT.INVERSE` is deprecated, you may use `LOI.STUDENT.INVERSE.BILATERALE` instead 
And of course the unilateral is named `LOI.STUDENT.INVERSE.N`.

I now see that the issue come from Excel method French names.

Thanks for your time and explanations (they make it crystal clear).
