### ISSUE TITLE
InterquartileRange, LowerQuartile, UpperQuartile returning wrong values?

### ISSUE THREAD

**Issue by kahaeia1** [mathnet/mathnet-numerics#755]
Hi,

I'm checking InterquartileRange, LowerQuartile, and UpperQuartile with values 1,2,3,4,5,7,8,10,12,14 and I seem to be getting different values than what I'm getting in online calculators. Could this be a bug?

Math.NET values:

InterquartileRange = 7.25
LowerQuartile = 2.9166
UpperQuartile = 10.166

Other online calculators:

InterquartileRange = 7.75
LowerQuartile = 2.75
UpperQuartile = 10.5

**Comment by cdrnet** [comment]
There are many different quantile definitions out there. Math.NET Numerics by default offers R8 quantiles, which are described as approximately median-unbiased regardless of the sample distribution, but also has an option to choose the quantile definition to remain compatible with other systems, by using QuantileCustom* instead of Quantile* functions.

I don't know what quantile definition these online calculators use.

Unfortunately these custom variants have not yet wired out to these shortcut functions (InterquartileRange, LowerQuartile, and UpperQuartile), but we could certainly add that.

**Comment by cdrnet** [comment]
Given your numbers, the online calculator may be using R6 quantiles (NIST, SPSS, ...)

**Comment by kahaeia1** [comment]
Ok that's good to know 🙂
