### ISSUE TITLE
Redistributing Intel MKL

### ISSUE THREAD

**Issue by deng0** [mathnet/mathnet-numerics#905]
I would greatly appreciate any further clarification on the subject of redistributing Intel MKL.

On https://numerics.mathdotnet.com/MKL.html#Licensing-Restrictions the following is stated:
"If you need to redistribute, buy a license from Intel. If unsure, contact the Intel sales team to clarify."

Is this information still accurate? 

If I'm not mistaken the oneAPI Toolkit is "available at no cost" 
https://www.intel.com/content/www/us/en/developer/articles/news/free-intel-software-developer-tools.html
and oneMKL "redistribution is allowed per the terms of the ISSL."
https://www.intel.com/content/www/us/en/developer/articles/license/onemkl-license-faq.html

I've also found the following thread:
https://community.intel.com/t5/Intel-oneAPI-Registration/MKL-License-Limited-patent-license/m-p/1296959#M1095

Or does this only refer to the oneAPI Toolkit and the version of MKL used in Math.NET.Numerics is different?
If that is the case what kind of license would one need to buy from intel?

**Comment by cdrnet** [comment]
Yes, I can confirm that this sentence is outdated and needs to be rephrased (and the MKL package licensing notes clarified).

The Numerics MKL packages used to be built using my own commercial license, but the new builds (currently prereleases) are built using oneAPI under the terms of the ISSL, as you have cited.

**Comment by diluculo** [comment]
To clarify the licensing issue, I asked a local reseller in Korea last week if I need to buy a license of Intel oneAPI Toolkit for **commercial use of MKL** and he said **no**.

[Wikipedia](https://en.wikipedia.org/wiki/Math_Kernel_Library) says:
Since April 2020, MKL has become part of oneAPI. Commercial support for oneMKL is available when purchased as part of oneAPI Base Toolkit.

The local reseller said that **commercial support** here means that you can get technical support, such as:
- Direct and private interaction with Intel’s support engineers, including the ability to submit confidential support requests
- Accelerated response time for technical questions and other product needs
- Free download access to all new product updates and continued access to older versions of the product
- Priority assistance for escalated defects and feature requests
- Access to a vast library of self-help documentation built from decades of experience with creating high-performance code
- Access to Intel public community forums supported by community technical experts and monitored by Intel engineers

**Comment by deng0** [comment]
Thanks to you both.
So in conclusion Intel probably wouldn't bother, if we would redistribute the version used in the latest stable version (MathNet.Numerics.MKL.Win-x64 2.5.0), and if we would use the new build (MathNet.Numerics.MKL.Win-x64 >= 3.0.0), there will definitely be no problem.
I guess, to be on the safe side, we'll use the new build then. Thanks again for your quick replies.

**Comment by cdrnet** [comment]
Just a small note, since you mentioned libiomp5md.dll: this is not actually Intel MKL, merely a dependency of it from the Intel C++ compiler for multi-threading (OpenMP). The parts of Intel MKL which we use is instead statically linked into the other binary, libMathNetNumericsMKL.dll (or MathNet.Numerics.MKL.dll in older releases).

**Comment by deng0** [comment]
ah, thx.

**Comment by cdrnet** [comment]
I've now clarified the license terms of the MKL Provider to be the [Intel Simplified Software License](https://numerics.mathdotnet.com/License-MKL.html). The mentioned remark on the website has been update and the NuGet packages will be updated to refer to this license as well on the next build.

**Comment by cdrnet** [comment]
Thank you for bringing this up.
