### ISSUE TITLE
OpenBLAS provider can't load the native library (Windows)

### ISSUE THREAD

**Issue by marklam** [mathnet/mathnet-numerics#907]
Sometime after alpha 03, the openblas package stopped working, failing with an exception

---- System.DllNotFoundException : Unable to load DLL 'libMathNetNumercisOpenBLAS' or one of its dependencies: The specified module could not be found. (0x8007007E)

I suspect it's because MathNet.Numerics.OpenBLAS.Win needs an update -  MathNet.Numerics.MKL.Win etc seem to have been refreshed, but the OpenBLAS library hasn't been published since 2015.

(Also, libMathNetNumercisOpenBLAS looks like a mis-type in 'Numerics')

**Comment by cdrnet** [comment]
Thanks for the note on the typo!

Yes, we need new releases of all the native providers (at least those we can still support) before finally releasing v5. Currently with the v5 pre-releases only the MKL provider for Windows is expected to be working already.

**Comment by kjbartel** [comment]
Sorry. I haven't been active in this project for a number of years as my work has taken me in a different direction. I did look at one point to add some native vector operations which are absent in OpenBLAS and also the use of some of the System.Numerics classes. If I recall correctly it was a bit harder to implement with newer versions of Math.Net due to changes to some classes making them sealed or internal. I haven't looked into it recently. The storage classes in particular would need to be looked at to use the CUDA provider and get any sort of performance out of it with multiple operations.

**Comment by cdrnet** [comment]
I've repackaged the old binaries in the new structure, which seems to be working:

https://github.com/mathnet/mathnet-integration-examples/commit/58955a7729c40035891b79de6734aff82158ead2

Can you confirm this works for you as well?

Of course the goal is to provide newer builds again as well, but this is not blocking the v5 release.

**Comment by cdrnet** [comment]
I'll close this assuming it is working - if not we can reopen it, please let me know. Thanks.

**Comment by marklam** [comment]
It works for me, thanks very much for the speedy fix!
